'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("luDefender.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property appLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("appLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property backGround() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backGround", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bigPatch4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bigPatch4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property closeButton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("closeButton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dasboardTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dasboardTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dashboard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dashboard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property disable_firewall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disable firewall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property enable_firewall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enable firewall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Event_log1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Event log1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property eventLogWallp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eventLogWallp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property eventLogWallp1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eventLogWallp1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property eventLogWallpaper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eventLogWallpaper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property file_shredder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("file shredder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property files_scanned_list() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("files scanned list", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property filesScanned() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filesScanned", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property filesScannedList() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filesScannedList", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fullScanLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fullScanLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 9fdb84667721a953898a080e5e944292
        '''
        '''0fbc3d37cc61b0755c5aa896762ce517
        '''209c7ecbfbfa74a6427f0dd9728d0a7c
        '''b70fc3f0051617363bbf05584d0cfed1
        '''0b0b3d67aabf57377586f7aa7525fd4d
        '''4fe497ea481d8492c065d78ff5e932ec
        '''e80084fb2e31ec07255d008d9782a14b
        '''3d616f85b32330c0f494adbaa35f27b3
        '''5ba6dec6076f47cfa179bc13583666d5
        '''6f90d7581e5e36c3e7d1607cc2963b89
        '''43963f7148786476e8532506279edf4f
        '''90acf7a8a3f9f29ee4c6dd4cefaa1470
        '''aa0d4613cbd221e892b602f4eb1d9f91
        '''40c67d90f42739e8b3ad6228e3346add
        '''d906dc607db7da070c40a43770cebfb1
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property hash_database() As String
            Get
                Return ResourceManager.GetString("hash_database", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ignoreThem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ignoreThem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lastScanLgo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lastScanLgo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lilPatch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lilPatch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lilPatch2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lilPatch2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lilPatch3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lilPatch3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property minButton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minButton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property purpleDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("purpleDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property purpleUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("purpleUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property quickScanLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("quickScanLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property removeThem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("removeThem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RO_dangerSystemStatus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RO_dangerSystemStatus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RO_dasboardTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RO_dasboardTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RO_deviceInDanger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RO_deviceInDanger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RO_disable_firewall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RO_disable firewall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RO_enable_firewall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RO_enable firewall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RO_Event_log() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RO_Event log", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RO_file_shredder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RO_file shredder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RO_files_scanned_list() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RO_files scanned list", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RO_filesScanned() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RO_filesScanned", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RO_fullScanLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RO_fullScanLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RO_ignoreThem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RO_ignoreThem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RO_lastScanLgo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RO_lastScanLgo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RO_logTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RO_logTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RO_quickScanLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RO_quickScanLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RO_removeThem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RO_removeThem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RO_scanningTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RO_scanningTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RO_scanStatus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RO_scanStatus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RO_settingDisplayedLanguage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RO_settingDisplayedLanguage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RO_settingRunOnStartup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RO_settingRunOnStartup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RO_settingScheduledScanning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RO_settingScheduledScanning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RO_settingsTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RO_settingsTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RO_startScan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RO_startScan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RO_statusSafeLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RO_statusSafeLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RO_stopScan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RO_stopScan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RO_toolTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RO_toolTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RO_url_checker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RO_url checker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RO_weGotYourBackLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RO_weGotYourBackLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Scanning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Scanning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scanningTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scanningTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scanStatus3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scanStatus3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property selectionThingy1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("selectionThingy1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property settingDisplayedLanguage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settingDisplayedLanguage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property settingRunOnStartup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settingRunOnStartup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property settingScheduledScanning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settingScheduledScanning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property settingsTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settingsTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property startScan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("startScan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property statusSafeLogo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("statusSafeLogo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stopScan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stopScan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tools() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tools", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property toolTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toolTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property url_checker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("url checker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 139520.aioc.qbgxl.com
        '''1717.1000uc.com
        '''360down7.miiyun.cn
        '''5.61.56.227shoreline.mips
        '''6bb9b4497037.xyz
        '''912648.aioc.qbgxl.com
        '''abissnet.net
        '''aefieiaehfiaehr.top
        '''airhobi.com
        '''aokdemc.com
        '''aosafrica.co.za
        '''api-ms.cobainaja.id
        '''api.52kkg.com
        '''api.discreetshare.com
        '''avastcsw.com
        '''bitkiselurunsiparis.com
        '''blackhattoolz.com
        '''bmcm.pw
        '''british-shorthair.es
        '''brknarikan.com
        '''bruiserbodies.com
        '''bruta.pl
        '''buscascolegios.diit.cl
        '''by.haory.cn
        '''cadenaderegalos.com
        '''cajgtus.com
        '''canconsulting.in
        '''cdaonline.com.ar
        '''chiptu [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property url_database() As String
            Get
                Return ResourceManager.GetString("url_database", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weGotYourBackLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weGotYourBackLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
